/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'IT000531' at '20/2/17 4:25 PM' with Gradle 2.14.1
 *
 * @author IT000531, @date 20/2/17 4:25 PM
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
